### PR TITLE
meta-java: Merge with upstream hardknott branch

### PR DESCRIPTION
**Pull request by shruthi-ravi**
#### Testing
Built runmode and safemode rootfs'.

#### Notes
Upstream ref: hardknott
AzDO [1781352](https://ni.visualstudio.com/DevCentral/_workitems/edit/1781352)

@ni/rtos

### CODE REVIEW

**Review by amstewart — APPROVED** [review]
I didn't realize we supported the new override syntax in hardknott. Was support for it recently backported to the btibake 1.50 ref, or am I just out-of-touch?

**Comment by shruthi-ravi** [comment]
It looks like the override syntax [commit](https://github.com/openembedded/bitbake/commit/f8d1bc200460fc1cb5cbf7a7d1986fd86424b22d) was made in July last year to bitbake/1.50.
Do we need a tracking item to update our recipes too?

**Comment by chaitu236** [comment]
> 



> It looks like the override syntax [commit](https://github.com/openembedded/bitbake/commit/f8d1bc200460fc1cb5cbf7a7d1986fd86424b22d) was made in July last year to bitbake/1.50. Do we need a tracking item to update our recipes too?

Latest bitbake [can support both of them](https://lists.openembedded.org/g/openembedded-core/message/160476). oe-core hardknott upstream still uses the old syntax so I don't think we have to update our recipes for hardknott.
Maybe we should do it only when we move away from hardknott?

**Comment by amstewart** [comment]
As long as bitbake 1.50 supports both, I'm fine if we get some of the new syntax in backports/upstream-merges like this. I would prefer to have both in the source than deal with the unnecessary risk of rebasing upstream commits to convert them back.

**Pull request merged**
